### ISSUE TITLE
CHECKOUT

### ISSUE THREAD

**Issue by antonijask** [mjoecohen/brightblock-oam#11]
These are new layout adjustments. 3 step Checkout.

![CHECKOUT-1](https://user-images.githubusercontent.com/47831018/54281766-be35fc80-459a-11e9-98f3-09c34d460f44.jpg)
![CHECKOUT-2-1](https://user-images.githubusercontent.com/47831018/54281767-be35fc80-459a-11e9-8812-0d6542285a86.jpg)
![CHECKOUT-2-2](https://user-images.githubusercontent.com/47831018/54281768-bece9300-459a-11e9-9424-bf49b096f050.jpg)
![CHECKOUT-3](https://user-images.githubusercontent.com/47831018/54281769-bf672980-459a-11e9-86b0-9fd356f986a4.jpg)

**Comment by antonijask** [comment]
see prototype - might help

https://xd.adobe.com/spec/15fc9862-e866-4e06-7cbd-a769ff31a277-63cd

**Comment by mjoecohen** [comment]
There is more work here for full workflow - can be raised in new tickets.
