### ISSUE TITLE
Artwork Page + Header Font Size

### ISSUE THREAD

**Issue by antonijask** [mjoecohen/brightblock-oam#3]
Artwork description text size needs adjustment.
Plus Header area. 

Header:
Search, Gallery, Artists... all links and text are 21pt
Instead of Cart icon we have text + number of items in the upper right corner

Artwork description:
Title 21pt
Rest 16pt
Artwork is registered on chain 14pt

Please follow the order of the description items (perhaps we don't need keywords atm, and other details like a year):
TITLE
ARTIST
SIZE
DESCRIPTION
PRICE 
BUY
Artwork is registered on the blockchain

![artowk_page-header-text-size](https://user-images.githubusercontent.com/47831018/54213540-d6e3db00-44e4-11e9-8be4-8f0b2126507c.jpg)
![Uploading Screenshot 2019-03-12 at 15.56.03.png…]()
![Uploading Screenshot 2019-03-12 at 15.58.19.png…]()

**Comment by mjoecohen** [comment]
Antonija - for responsiveness the font sizes are measured in rem / em and %

I set the header / footer links to 1em and 1.2em respectively.

I tidied up the title / other text on the artwork page to be vanilla  <h2> and <p> tags zwhich get defaults font-size of 2.0rem and 1.1em respec.

Will close this for now as its probably something we will need to revisit more comprehensively.

**Comment by mjoecohen** [comment]
Closing as we need FED for this.
