### ISSUE TITLE
Green Color

### ISSUE THREAD

**Issue by antonijask** [mjoecohen/brightblock-oam#4]
Please change green color everywhere, including the buttons.
I will add later other values, hover, etc. 

GREEN = 00ac98

<img width="167" alt="Screenshot 2019-03-12 at 16 36 05" src="https://user-images.githubusercontent.com/47831018/54213673-11e60e80-44e5-11e9-82b7-144e733d319f.png">

**Comment by mjoecohen** [comment]
Antonija - you need to pick colours from here

https://mdbootstrap.com/docs/vue/css/colors/

so for example the colour 00ac98 is not a choice but if I set the classes on the button to;

class="btn teal lighten-1" 

it gets pretty close. If you give me the colour classes from there its easy to change the colours.
