### ISSUE TITLE
transitions - switching from page to page

### ISSUE THREAD

**Issue by antonijask** [mjoecohen/brightblock-oam#7]
When we switch from page to page, for a moment old data is displayed
For example, we go from Gallery > Artwork > Artwork page, for a moment the old UI shows up, the old green buttons, or steps, such as "proceed with checkout" - when we should directly switch to payment details

**Comment by mjoecohen** [comment]
Agree.

Two issues - 1. colour of buttons (missed these first time round). 2. transition to new page needs to be smoother. On it..
