### ISSUE TITLE
Gallery Image Display + Image description

### ISSUE THREAD

**Issue by antonijask** [mjoecohen/brightblock-oam#9]
Ideally, images should be displayed left aligned (see attached preview)

The image description, instead centrally aligned, should in left upper corner, 
with small padding (about 20p). 

Please give black overlay transparency 75%

![images-display](https://user-images.githubusercontent.com/47831018/54275936-43fe7b80-458c-11e9-9cac-0f6447e6c0c5.jpg)

**Comment by mjoecohen** [comment]
done
